posts/forms.py
from wtforms import Form, StringField, TextAreaField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from wtforms import ValidationError


class PostForm(Form):
    title = StringField('Title', validators=[DataRequired(message="Enter title of the post please.")])
    body = TextAreaField('Body', validators=[DataRequired(message="Enter text of the post please.")])


class ContactUsForm(Form):
    name = StringField('Name', validators=[DataRequired(message="Enter your name please.")])
    email = StringField('Email', validators=[DataRequired(message="Enter your email please."), Email()])
    telephone = StringField('Telephone', validators=[DataRequired(message="Enter your telephone please."),
                                                     Length(min=10, max=13)])
    subject = StringField('Subject', validators=[DataRequired(message="Enter the subject please.")])
    message = TextAreaField('Message')
    submit = SubmitField("Send")


class RegistrationForm(Form):
    username = StringField('Username', [DataRequired(message="Enter your username please."),
                                        Length(min=4, max=100)])
    email = StringField('Email Address', [DataRequired(message="Enter your email please."),
                                          Length(min=6, max=100), Email()])
    password = PasswordField('New Password', [
        DataRequired(message="Enter your password please."), Length(min=6, max=20),
        EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('I accept the Terms of Service and Privacy Notice (updated Jan 22, 2020)',
                              [DataRequired(DataRequired(message="Accept the terms."))])
    submit = SubmitField("Send")

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_security import login_required

from app import db
from models.post import Post
from models.tag import Tag
from .forms import PostForm

posts_ = Blueprint('posts', __name__, template_folder='templates')


# http://localhost/blog/create
@posts_.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    form = PostForm()

    if request.method == 'POST':
        title = request.form.get('title', '')
        body = request.form.get('body', '')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
            flash('Post was successfully created.')
        except:
            flash('Post wasn\'t added to db.')
        return redirect(url_for('posts.index'))

    elif request.method == 'GET':
        return render_template('posts/create_post.html', form=form)


@posts_.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        flash('Post was successfully edited.')
        return redirect(url_for('posts.post_detail', slug=slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts_.route('/')
def index():
    q = request.args.get('q')

    # /blog/?page=2 (args after =)
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(
            Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=3)

    return render_template('posts/index.html', posts=posts, pages=pages)


# http://localhost/blog/first-post
@posts_.route('/<string:slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://localhost/blog/tag/python
@posts_.route('/tag/<string:slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
Create new post
{% endblock %}


{% block content %}
<section class="blog pt-100 pb-100">
    <div class="col-xl-12">
        <div class="container">
            <div class="col-xl-6 mx-auto text-center">
                <div class="section-title mb-100">
                    <p>create post</p>
                    <h4>New Post</h4>
                </div>
            </div>
            <form class="contact-form input contact-form textarea" action="{{url_for('posts.create_post')}}" method="post">
                {% for field in form %}
                <div class="form-group">
                    {% if field.name == 'body' %}
                    {{ field(placeholder='Body') }}
                    {% else %}
                    {{ field(placeholder='Title') }}
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">Create</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

posts/templates/posts/edit_post.html
{% extends "base.html" %}

{% block title %}
Edit post
{% endblock %}


{% block content %}
<section class="blog pt-100 pb-100">
    <div class="col-md-12">
        <div class="container">
            <h1 class="text-center mt-3 mb-5">Edit post</h1>
            <form action="{{url_for('posts.edit_post', slug=post.slug)}}" method="post">
                {% for field in form %}
                <div class="form-group">
                    {{ field.label(class='control-label') }}
                    {{ field(class='form-control') }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">Update</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}
{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
Posts
{% endblock %}

{% block content %}
<section class="blog pt-100 pb-100">
    <div class="col-md-12">
        <div class="container">
            <div>
                {% for message in get_flashed_messages() %}
                    {% if message == 'Post was successfully created.' or
                        message == 'Post was successfully edited.' %}
                        <div class="badge badge-success">{{ message }}</div>
                    {% else %}
                        <div class="badge badge-danger">{{ message }}</div>
                    {% endif %}
                {% endfor %}
                <div class="col-xl-6 mx-auto text-center">
                    <div class="section-title mb-100">
                        <p>all posts</p>
                        <h4>Posts</h4>
                    </div>
                </div>

                {% for post in pages.items %}
                <div>
                    <hr>
                    <a href="{{url_for('posts.post_detail', slug=post.slug)}}" style="color: white">{{post.title}}</a>
                    <div class="text-right">
                        {% if current_user.has_role('admin') %}
                        <a href="{{url_for('posts.edit_post', slug=post.slug)}}" class="btn btn-secondary"
                           role="button">Edit</a>
                        {% endif %}
                    </div>
                    <hr>
                </div>
                {% endfor %}

                <nav>
                    <ul class="pagination justify-content-center" style="margin-top: 100px">
                        <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
                            <a class="page-link" href="./?page={{pages.prev_num}}" tabindex="-1">Previous</a>
                        </li>

                        {% for page in pages.iter_pages() %}
                        <li {% if page== pages.page %} class="active" {% endif %}>
                            <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                        </li>
                        {% endfor %}

                        <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
                            <a class="page-link" href="./?page={{pages.next_num}}">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}
{{post.title}}
{% endblock %}


{% block content %}
<section class="blog pt-100 pb-100">
    <div class="col-md-12">
        <div class="container">
            <div>
                <hr>
                <div class="col-xl-6 mx-auto text-center">
                    <div class="section-title mb-100">
                        <p>post details</p>
                        <h4>{{post.title}}</h4>
                    </div>
                </div>
                <div class="">
                    {% for tag in tags %}
                    <a href="{{url_for('posts.tag_detail', slug=tag.slug)}}" style="text-decoration:none">
                        <span class="badge badge-warning mt-2 mb-5">{{tag.name}}</span>
                    </a>
                    {% endfor %}
                </div>
                <div class="">
                    <p>{{post.body}}</p>
                </div>
                <span class="badge" style="padding-left: 0">Posted {{post.created}}</span>
                {% if current_user.is_authenticated %}
                <span class="badge" style="padding-left: 0">Posted by {{current_user.username}}</span>
                {% endif %}
            </div>
            <hr>
        </div>
    </div>
</section>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends "base.html" %}

<style>
    .blog {
        background-image: url("http://infinityflamesoft.com/html/abal-preview/assets/img/contact_back.jpg");
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        position: relative;
        z-index: 2;
        color: #fff;
    }
    .blog:before {
        position: absolute;
        content: "";
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        background-color: #333;
        z-index: -1;
        opacity: .85;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=85)";
    }
</style>

{% block title %}
{{tag.name}}
{% endblock %}

{% block content %}
<section class="blog pt-100 pb-100">
    <div class="col-md-12">
        <div class="container">
            <div>
                <h1 class="text-center mt-3 mb-5" style="margin-top: 30px">
                    <p class="badge badge-warning">{{tag.name}}</p>
                </h1>
                <div class="post">
                    {% for post in posts %}
                    <p><a href="{{url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}
{% endblock %}